/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HintTrackerIndexRouteImport } from './routes/hint-tracker/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HintTrackerIndexRoute = HintTrackerIndexRouteImport.update({
  id: '/hint-tracker/',
  path: '/hint-tracker/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hint-tracker/': typeof HintTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hint-tracker': typeof HintTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hint-tracker/': typeof HintTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hint-tracker/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hint-tracker'
  id: '__root__' | '/' | '/hint-tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HintTrackerIndexRoute: typeof HintTrackerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hint-tracker/': {
      id: '/hint-tracker/'
      path: '/hint-tracker'
      fullPath: '/hint-tracker/'
      preLoaderRoute: typeof HintTrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HintTrackerIndexRoute: HintTrackerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
